# Use Node.js to build the React app
#FROM node:18 AS build
FROM cagbu-dev-docker-tp.dockerhub-phx.oci.oraclecorp.com/node:22.14.0 AS build
# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Build the React app
RUN npm run build

# Use Nginx to serve the built React app
# FROM nginx:alpine
FROM cagbu-dev-docker-tp.dockerhub-phx.oci.oraclecorp.com/org.apache.httpd:httpd / 2.2.32
# FROM httpd:alpine

# Copy built frontend files to Nginx public folder
#COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/build /usr/local/apache2/htdocs/

# Expose the frontend port
EXPOSE 80

# Start Nginx
#CMD ["nginx", "-g", "daemon off;"]
CMD ["httpd", "-D", "FOREGROUND"]
