version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://chakriraman:Cha1234@cluster0.lc8qico.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=chakriraman

    

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
