# Use an official Node.js image as the base
#FROM node:18
FROM cagbu-dev-docker-tp.dockerhub-phx.oci.oraclecorp.com/node:22.14.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend files
COPY . .

# Expose the backend port
EXPOSE 5123
# Command to run the backend
CMD ["npm", "start"]
